# Server Configuration
spring.application.name=logiq-backend
server.port=8080

# Database Connection (Telling Java where MySQL is)
spring.datasource.url=jdbc:mysql://localhost:3306/logiq_db
spring.datasource.username=root
spring.datasource.password=

# Hibernate (Telling Java how to handle the tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true