# Server Configuration
spring.application.name=logiq-backend
server.port=8080

# Database Connection (In-Memory H2 for simple bootable starter)
spring.datasource.url=jdbc:h2:mem:logiq_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (Telling Java how to handle the tables)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true